buggy_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'buggy_app'

urlpatterns = [

    url(r'^carlist$',views.CarListView.as_view(),name='car_list'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^booklist$',views.BookingListView.as_view(),name='book_list'),

    url(r'^carlist/(?P<pk>\d+)/$',views.CarDetailView.as_view(),name='details'),
    url(r'^booking/',views.BookingView.as_view(),name='car_booking'),
    url(r'^booklist/(?P<pk>\d+)/$',views.BookingDetailView.as_view(),name='detail'),
    url(r'^create/$',views.BookingCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.BookingUpdateView.as_view(),name='update'),
    url(r'^home/$',views.HomeView.as_view(),name='home'),
    url(r'^services/$',views.ServicesView.as_view(),name='services'),
    url(r'^export/xls/$', views.export_booking_xls, name='export_booking_xls'),
    url(r'^export/xls/car/$', views.export_car_xls, name='export_car_xls'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^pop/$',views.PopView.as_view(),name='pop'),
    url(r'^create_driver/$',views.DriverCreateView.as_view(),name='create_driver'),
    url(r'^driverlist/(?P<pk>\d+)/$',views.DriverDetailView.as_view(),name='driverdetail'),
    url(r'^driverlist$',views.DriverListView.as_view(),name='driver_list'),
    url(r'^dupdate/(?P<pk>\d+)/$',views.DriverUpdateView.as_view(),name='dupdate'),

]

joinbuggy/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from buggy_app import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^buggy_app/',include('buggy_app.urls',namespace='buggy_app')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buggy_app/forms.py
from django import forms
from django.contrib.auth.models import User

from buggy_app.models import Booking,UserProfileInfo
from django.forms import ModelForm
from django.forms import extras
from datetimewidget.widgets import TimeWidget
from django.forms.extras.widgets import SelectDateWidget
from django import forms
from datetimepicker.helpers import js_loader_url
from bootstrap_datepicker_plus import TimePickerInput

import datetime




class BookingForm(ModelForm):

    class Meta:
        model = Booking
        widgets = {
            'times_pick': TimePickerInput(),

        }
        fields = ('first_name','last_name','email','book_car','contact_number','times_pick',)



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

buggy_app/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)

from .  import models
from buggy_app.models import Booking , Car
from buggy_app.forms import BookingForm , UserForm ,UserProfileInfoForm

from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import xlwt

from django.utils import timezone
import pytz
from django.template.loader import get_template
from django.conf import settings
from django.core.mail import  send_mail





class IndexView(TemplateView):

    template_name = 'buggy_app/index.html'

class HomeView(TemplateView):
    template_name = 'buggy_app/home.html'

class ServicesView(TemplateView):
    template_name = 'buggy_app/services.html'

class BookingListView(ListView):
    context_object_name = 'books'
    model = models.Booking


class BookingDetailView(DetailView):
    context_object_name = 'booking_details'
    model = models.Booking
    template_name = 'buggy_app/booking_detail.html'


class PopView(TemplateView):

    template_name = 'buggy_app/pop.html'



def detail(request, blog_id):
	detailblog = get_object_or_404(Blog, pk=blog_id)
	return render(request, 'blog/detail.html', {'blog':detailblog})


class BookingCreateView(CreateView):
    fields = ("customer_name","book_car","booking_end_date","rental_price","is_approved")
    model = models.Booking


class BookingUpdateView(UpdateView):
    fields = ("customer_name","book_car","booking_end_date","rental_price","is_approved")
    model = models.Booking


@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('buggy_app:home'))

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('buggy_app:home'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'buggy_app/login.html', {})


class CarListView(ListView):
    context_object_name = 'cars'
    model = models.Car

    def get_queryset(self):
        qs = super(CarListView, self).get_queryset()
        qs = qs.filter(is_available_car=True)
        return qs


class CarDetailView(DetailView):
    context_object_name = 'car_details'
    model = models.Car
    template_name = 'buggy_app/car_detail.html'


class BookingView(FormView):
    template_name = 'buggy_app/booking.html'
    form_class = BookingForm
    models = Booking
    def form_valid(self, form):
        car_id = self.request.GET.get('car', '')
        car = Car.objects.get(id=car_id)
        car.is_available_car = True
        car.save()
        form.save()
        subject = "Thnakyou for joining Joinbuggy"
        from_email = settings.EMAIL_HOST_USER
        to_email = form.cleaned_data.get('email')
        join_message = """Your booking is placed we will contact you later """
        send_mail(subject=subject,from_email=from_email,recipient_list=[to_email],message=join_message,fail_silently=False )


        return super(BookingView, self).form_valid(form)


    success_url = reverse_lazy('buggy_app:pop')

    def get_context_data(self, **kwargs):
        # kwargs['car'] is the car booking now!
        try:
            kwargs['car'] = Car.objects.get(id=self.request.GET.get('car', ''))
        except (Car.DoesNotExist, ValueError):
            kwargs['car'] = None
        return super(BookingView, self).get_context_data(**kwargs)

    # if you still want to keep select car in form,and auto select this car do as:
    def get_initial(self):
        initial = super(BookingView, self).get_initial()
        if 'car' in self.request.GET:
            try:
                initial['book_car'] = Car.objects.get(id=self.request.GET['car'])
            except (Car.DoesNotExist, ValueError):
                pass
        return initial



def send_emails(first_name, last_name, to_email):
    #get template
    htmly = get_template('buggy_app/welcome.html')
    #create a context
    d = {'first_name':first_name, 'last_name':last_name}
    subject, from_email, to = 'Subject line', settings.EMAIL_HOST_USER, to_email
    #pass the context to html template
    html_content = htmly.render(d)
    msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
class DriverListView(ListView):
    model = models.Driver
    context_object_name = 'driver'


    def get_queryset(self):
        qs = super(DriverListView, self).get_queryset()
        qs = qs.filter(driver_agree_terms=True)
        return qs


class DriverDetailView(DetailView):
    context_object_name = 'driver_details'
    model = models.Driver
    template_name = 'buggy_app/driver_detail.html'
class DriverCreateView(CreateView):
    fields = ("driver_firstname","driver_lastname","driver_stripe_id","driver_email","driver_dmv_license","driver_tlc_license","driver_notes","driver_dob","driver_license_date","driver_tlc_license_date","driver_foreign_license_date","driver_accidents","driver_points","driver_police_report","driver_current_agreement_id","driver_city","driver_state","driver_street_address","driver_cap_insurance_state","driver_insurance_note","driver_link_mvr","driver_ddc_pic","driver_license_pic")
    model = models.Driver
class DriverUpdateView(UpdateView):
    fields = ("driver_firstname","driver_lastname","driver_stripe_id","driver_email","driver_dmv_license","driver_tlc_license","driver_notes","driver_dob","driver_license_date","driver_tlc_license_date","driver_foreign_license_date","driver_accidents","driver_points","driver_police_report","driver_current_agreement_id","driver_city","driver_state","driver_street_address","driver_cap_insurance_state","driver_insurance_note","driver_link_mvr","driver_ddc_pic","driver_license_pic")

    model = models.Driver
class BookingCreateView(CreateView):
    fields = ("customer_name","book_car","booking_end_date","rental_price","is_approved","times_pick")
    model = models.Booking


class BookingUpdateView(UpdateView):
    fields = ("first_name","book_car","rental_price","is_approved","times_pick")

    model = models.Booking

def export_booking_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="bookings.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Bookings')


    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Booking Name', 'Drivers', 'Cars Booked', 'Rental Price','Admin Approvel' ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Booking.objects.all().values_list('booking_name', 'customer_name', 'book_car',  'rental_price', 'is_approved')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response
def export_car_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="cars.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Bookings')


    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['CAr Name', 'reg_no', 'description', 'power_hp','transmission','seats','air_bags ', 'fuel_type' ,'is_available_car' ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Car.objects.all().values_list('car_name', 'reg_no', 'description',  'power_hp', 'transmission','seats','air_bags','fuel_type','is_available_car',)
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response


'''
def booking_create(request,pk):
    book_car = get_object_or_404(Car, pk=pk)
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():

            booking = form.save(commit=False)
            booking.book_car = book_car

templates/buggy_app/adminbase.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}


<head>
<meta charset="UTF-8">
<title>Buggy Admin</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="Car Rental One Page HTML Template">
<meta name="keywords" content="one page, html, template, car, car rental, taxi, cab, booking, responsive, business">
<meta name="author" content="sharjeel anjum">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Bootstrap css -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

<!-- Fontawesome css -->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<!-- Magnific-popup css -->
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<!-- Rev Slider css -->

<!-- Owl Carousel css -->
<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">

<!-- Main css -->
<link rel="stylesheet" href="{% static 'css/styleadmin.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">


</head>



    <body>

        <div class="navbar custom-navbar wow fadeInDown" data-wow-duration="2s" role="navigation" id="header">
          <div class="container">

            <!-- NAVBAR HEADER -->
            <div class="navbar-header">
              <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> <span class="icon icon-bar"></span> </button>
              <!-- lOGO TEXT HERE -->
              <a href="index.html" class="navbar-brand">Admin <span> BUGGY TLC </span></a> </div>

            <!-- NAVIGATION LINKS -->
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'buggy_app:home' %}" class="smoothScroll">Home</a></li>
                <li><a href="{% url 'admin:index' %}" class="smoothScroll">Admin</a></li>


          <li><a href="{% url 'logout' %}"class="smoothScroll">Logout</a></li>
        {% else %}
          <li><a href="{% url 'buggy_app:user_login' %}" class="smoothScroll">Login</a></li>
        {% endif %}
        <li><a href="{% url 'buggy_app:services' %}" class="smoothScroll">Services</a></li>
        <li><a href="{% url 'buggy_app:car_list' %}" class="smoothScroll">CAr List </a></li>




                <li><span class="calltxt"><i class="fa fa-phone" aria-hidden="true"></i> 123 456 7890</span></li>
              </ul>
            </div>
          </div>
        </div>


























<div class="container">



      {% block body_block %}

      {% endblock %}
</div>
<!-- Bootstrap -->
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>




<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>

<!-- Popup -->

<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>

<!-- Carousel -->
<script src="{% static 'js/owl.carousel.js' %}"></script>



<!-- Sticky Header -->
<script src="{% static 'js/jquery.sticky.js' %}"></script>


<!-- Parallax -->
<script src="{% static 'js/jquery.parallax.js' %}"></script>


<!-- Counter -->
<script src="{% static 'js/counter.js' %}"></script>

<script src="{% static 'js/smoothscroll.js' %}"></script>


<!-- Custom -->
<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/buggy_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <script type="text/javascript" src="/bower_components/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/bower_components/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/i.css' %}">
    <script src="{% static 'js/side.js' %}"></script>




<title>
  Buggy
  {# Title Extensions go inside the block#}
  {% block title_block %}

  {% endblock %}
</title>
{# MEDIUM STYLE EDITOR#}
      <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


{# Fonts#}
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>

    <body>

          <nav class="navbar navbar-default no-margin">
           <!-- Brand and toggle get grouped for better mobile display -->
           <div class="navbar-header fixed-brand">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" id="menu-toggle">
     <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
           </div>
        </nav>
        <div id="wrapper">
           <!-- Sidebar -->
           <div id="sidebar-wrapper">
              <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
                 <li class="active">
                    <a href=""><span class="fa-stack fa-lg pull-left"><i class="fa fa-dashboard fa-stack-1x "></i></span> Dashboard</a>
                    <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                       <li><a href="{% url 'buggy_app:car_list' %}">CAR Menu</a></li>
                    </ul>
                 </li>
                 <li>
                    <a href="{% url 'buggy_app:services' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
                 </li>
                 {% if user.is_authenticated %}

           <li>
              <a href="{% url 'logout' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-cloud-download fa-stack-1x "></i></span>Logout</a>
           </li>
           <li>
              <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Shortcut</a>
              <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                 <li><a href="{% url 'admin:index' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Admin</a></li>
                 <li><a href="{% url 'buggy_app:home' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Admin Home</a></li>
              </ul>
           </li>
           <li>
              <a href="#"><span class="fa-stack fa-lg pull-left"><i class="fa fa-flag fa-stack-1x "></i></span>Booking</a>
              <ul class="nav-pills nav-stacked" style="list-style-type:none;">

                    <li><a href=""><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>Create</a></li>
                    <li><a href="{% url 'buggy_app:book_list' %}"><span class="fa-stack fa-lg pull-left"><i class="fa fa-server fa-stack-1x "></i></span>List</a></li>

              </ul>
           </li>

         {% else %}
           <li><a href="{% url 'buggy_app:user_login' %}" class="smoothScroll">Login</a></li>
         {% endif %}






              </ul>
           </div>


<div class="container">



      {% block body_block %}

      {% endblock %}
</div>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js" </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
  </html>

templates/buggy_app/booking_detail.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}
<div class="container">

  <div class="jumbotron">
  <h2>Booking detail</h2>
<div class="container">
  <div class="col-12">


  <div class="card" style="width:400px">
    <img class="card-img-top" src="{% static "img/booked.png" %}" alt="Card image" style="width:100%">
    <div class="card-body">
      <h3 class="card-title">Id #  {{booking_details.id}} | Name :  {{booking_details.customer_name}} </h3>
      <p class="card-text"> The {{booking_details.book_car}} is booked in $ {{booking_details.rental_price}} from {{booking_details.booking_start_date}} to {{booking_details.booking_end_date}}. <br> Admin Aprroved = {{booking_details.is_approved}} </p>
      <a class='btn btn-warning' href="{% url 'buggy_app:update' pk=booking_details.pk %}">Update</a>

    </div>

    </div>
    </div>
    </div>
        </div>





{% endblock %}

templates/buggy_app/booking_list.html
{% extends "buggy_app/base.html" %}


{% block body_block %}
{% load staticfiles %}
<div class="container">
  <link rel="stylesheet" href="{% static 'css/table.css' %}">




  <div class="jumbotron">

    <h1>Welcome to the list of Booking </h1>


  </div>

  <div class="col-12">

  <img src="{% static "img/bg.png" %}" class="img-fluid" alt="Responsive image">
  </div>

    </div>
    <div class="container">
      <div class="row text-center padding">

      <div class="col-cs-12 col-sm-6 col-md-6 col-lg-3">
    <table>
  <thead >
    <tr>
      <th>ID</th>
      <th>Booking Name</th>
      <th>Customer Name</th>
      <th>book_car</th>
      <th>booking_start_date</th>
      <th>booking_end_date</th>
      <th>rental_price</th>
        <th>times_pick</th>
          <th>is_approved</th>
            <th>Detail Link    </th>

</tr>

  </thead>

  {% for books in books %}

  <tbody>
    <tr>
      <td>{{books.id}}</td>
      <td>
            {{books.booking_name}}</td>
      <td>{{books.customer_name}}
            </td>
      <td>{{books.book_car}}
            </td>
      <td>{{books.booking_start_date}}
            </td>
      <td>{{books.booking_end_date}}
            </td>
            <td>{{books.rental_price}}
            </td>


      <td>{{books.times_pick}}
      </td>

            <td>{{books.is_approved}}
            </td>
                  <td><a href="{% url 'buggy_app:detail' pk=books.pk %}" class="btn btn-large">BOOK a Car</a>
                  </td>
</tr>
  </tbody>
  {% endfor %}

</table>




</div>
</div>
</div>

{% endblock %}

templates/buggy_app/login.html
{% extends 'buggy_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'buggy_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
  {% endblock %}